# Generated by Django 4.0.3 on 2022-05-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="is_default",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Igreja sede?",
            ),
        ),
    ]
