# Generated by Django 4.0.3 on 2022-04-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MembrerType",
            new_name="MemberType",
        ),
    ]
