# Generated by Django 4.0.3 on 2022-04-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0002_rename_membrertype_membertype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "verbose_name": "Membro",
                "verbose_name_plural": "Membros",
            },
        ),
        migrations.AlterModelTable(
            name="membertype",
            table="church_member_type",
        ),
    ]
