# Generated by Django 4.0.3 on 2022-04-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_address_table"),
        ("church", "0003_alter_member_options_alter_membertype_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="code",
            field=models.CharField(
                default=2,
                help_text="Usado para identificar a igreja",
                max_length=30,
                unique=True,
                verbose_name="Código",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="church",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="church", to="church.member"
            ),
        ),
        migrations.AlterField(
            model_name="membertype",
            name="code",
            field=models.CharField(
                default=1,
                help_text="Usado para identificar o tipo de membro",
                max_length=30,
                unique=True,
                verbose_name="Código",
            ),
            preserve_default=False,
        ),
    ]
