# Generated by Django 4.0.3 on 2022-04-07 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0004_alter_church_address_alter_church_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="church",
            name="members",
        ),
        migrations.AddField(
            model_name="member",
            name="church",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="church.church",
                verbose_name="Igreja",
            ),
            preserve_default=False,
        ),
    ]
