# Generated by Django 4.0.3 on 2022-04-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagehome',
            options={'ordering': ['order'], 'verbose_name': 'Imagens da Home'},
        ),
        migrations.AlterModelOptions(
            name='imagehomethroughmodel',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='imagehomethroughmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem'),
        ),
    ]
