# Generated by Django 4.0.3 on 2022-05-10 00:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "config",
            "0002_churchbodysection_alter_homepageconfig_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageconfig",
            name="body_content",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Seção pastores"
            ),
        ),
    ]
