# Generated by Django 4.0.3 on 2022-04-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_alter_imagehomethroughmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageconfig",
            name="maps_frame",
            field=models.TextField(
                blank=True, null=True, verbose_name="Iframe do Google Maps"
            ),
        ),
    ]
