# Generated by Django 4.0.3 on 2022-05-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_homepageconfig_body_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageconfig",
            name="body_title",
            field=models.CharField(
                help_text="Subtítulo da seção Pastores",
                max_length=200,
                null=True,
                verbose_name="Título",
            ),
        ),
    ]
