# Generated by Django 4.0.3 on 2022-05-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_homepageconfig_body_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageconfig",
            name="body_title",
            field=models.CharField(
                help_text="Subtítulo da seção Pastores",
                max_length=200,
                null=True,
                verbose_name="Subtítulo",
            ),
        ),
    ]
