# Generated by Django 4.0.3 on 2022-05-11 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0003_church_active"),
        ("config", "0005_alter_homepageconfig_body_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageconfig",
            name="church",
            field=models.ForeignKey(
                blank=True,
                help_text="Igreja ao qual a configuração estará associada",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_config",
                to="church.church",
            ),
        ),
    ]
