# Generated by Django 4.0.3 on 2022-04-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="text",
        ),
    ]
