# Generated by Django 4.0.3 on 2022-04-06 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-publish_date"],
                "verbose_name": "Publicação",
                "verbose_name_plural": "Publicações",
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="published",
        ),
        migrations.RemoveField(
            model_name="post",
            name="review_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reviewed_by",
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de revisão"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Comentário com até 200 caracteres",
                        max_length=200,
                        verbose_name="Comentário",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisão",
                "verbose_name_plural": "Revisões",
                "ordering": ["-review_date"],
            },
        ),
    ]
