# Generated by Django 4.0.3 on 2022-04-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_reviews_review_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="title",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="comment",
            field=models.TextField(
                help_text="Comentário com até 500 caracteres",
                max_length=500,
                verbose_name="Comentário",
            ),
        ),
    ]
