# Generated by Django 4.0.3 on 2022-04-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_reviews_title_alter_reviews_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="review_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Data de revisão"
            ),
        ),
    ]
