# Generated by Django 4.0.3 on 2022-04-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Ativo"),
        ),
    ]
