# Generated by Django 4.0.3 on 2022-06-02 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Crédito"),
                            (1, "Débito"),
                            (2, "Depósito"),
                            (3, "Boleto"),
                        ],
                        default=0,
                        verbose_name="Tipo de pagamento",
                    ),
                ),
                (
                    "location_type",
                    models.IntegerField(
                        choices=[(0, "Evento"), (1, "Loja")],
                        verbose_name="Tipo local",
                    ),
                ),
                (
                    "brand",
                    models.IntegerField(
                        choices=[
                            (1, "Visa"),
                            (2, "Mastercard"),
                            (3, "Elo"),
                            (4, "Amex"),
                            (5, "Cabal"),
                            (6, "Hipercard"),
                            (7, "Depósito"),
                            (8, "Desconhecido"),
                        ],
                        verbose_name="Bandeira",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Valor"
                    ),
                ),
                (
                    "number_of_installments",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantidade de parcelas",
                    ),
                ),
                (
                    "date_of_payment",
                    models.DateTimeField(
                        null=True, verbose_name="Data de pagamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=None, null=True, verbose_name="Data pagamento"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "tax_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Taxa",
                    ),
                ),
                (
                    "week",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Semana"
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(default=0, verbose_name="Sequência"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="financial.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela",
                "verbose_name_plural": "Parcelas",
            },
        ),
    ]
