# Generated by Django 4.0.3 on 2022-06-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventpaymentoption_max_installment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpaymentoption",
            name="max_installment",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Numero máximo de parcelas"
            ),
        ),
    ]
