# Generated by Django 4.0.3 on 2022-05-29 03:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("church", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ordem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagens da página principal",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Página principal"), (2, "Ministérios")],
                        help_text="Tipo de página",
                        verbose_name="Tipo de página",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Ativa"),
                ),
                (
                    "maps_frame",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Iframe do Google Maps",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        help_text="Igreja ao qual a configuração estará associada",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_config",
                        to="church.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração da Página",
                "verbose_name_plural": "Configurações das Páginas",
            },
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.PositiveSmallIntegerField(
                        help_text="As seções serão apresentadas em ordem decrescente",
                        verbose_name="Número da seção",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="título do conteúdo",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Conteúdo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.pageconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo da Página",
                "verbose_name_plural": "Conteúdos da Página",
                "ordering": ["section"],
            },
        ),
        migrations.CreateModel(
            name="MinistryChurch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nome completo"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.pageconfig",
                    ),
                ),
            ],
            options={
                "ordering": ("page", "order"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageThroughModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ordem"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.imagehome",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.pageconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem",
                "verbose_name_plural": "Imagens",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContactMeans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "whatsapp"),
                            ("email", "email"),
                            ("facebook", "facebook"),
                        ],
                        max_length=30,
                        verbose_name="Forma de contato",
                    ),
                ),
                (
                    "contact",
                    models.CharField(max_length=200, verbose_name="Contato"),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.ministrychurch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChurchBodySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nome completo"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="church.membertype",
                        verbose_name="Tipo de membro",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.pageconfig",
                    ),
                ),
            ],
            options={
                "ordering": ("page", "order"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinistryPageConfig",
            fields=[],
            options={
                "verbose_name": "Configuração da Página dos Ministérios",
                "verbose_name_plural": "Configurações da Páginas dos Ministérios",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("config.pageconfig",),
        ),
    ]
