# Generated by Django 4.0.3 on 2022-05-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_alter_imagehome_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MinistryChurch",
            new_name="MinistryChurchSection",
        ),
        migrations.AlterModelOptions(
            name="churchbodysection",
            options={
                "ordering": ("page", "order"),
                "verbose_name": "Membro da Igreja",
                "verbose_name_plural": "Seções dos Membros da Igreja",
            },
        ),
        migrations.AlterModelOptions(
            name="imagehome",
            options={
                "ordering": ["order"],
                "verbose_name": "Imagens das páginas",
            },
        ),
        migrations.AlterModelOptions(
            name="ministrychurchsection",
            options={
                "ordering": ("page", "order"),
                "verbose_name": "Ministério da Igreja",
                "verbose_name_plural": "Seções dos Ministérios da Igreja",
            },
        ),
        migrations.AlterModelOptions(
            name="ministrypageconfig",
            options={
                "verbose_name": "Página dos Ministérios",
                "verbose_name_plural": "Páginas dos Ministérios",
            },
        ),
        migrations.AlterModelOptions(
            name="pageconfig",
            options={
                "verbose_name": "Página Inicial",
                "verbose_name_plural": "Páginas Iniciais",
            },
        ),
        migrations.DeleteModel(
            name="ContactMeans",
        ),
    ]
