# Generated by Django 4.0.3 on 2022-05-29 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0002_ministry"),
        (
            "config",
            "0004_rename_ministrychurch_ministrychurchsection_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ministrychurchsection",
            name="ministry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="church.ministry",
                verbose_name="Ministério",
            ),
        ),
    ]
