# Generated by Django 4.0.3 on 2022-05-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_ministrychurchsection_ministry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MinistryPageConfig",
        ),
        migrations.AlterModelOptions(
            name="pageconfig",
            options={
                "verbose_name": "Página",
                "verbose_name_plural": "Páginas",
            },
        ),
        migrations.AddField(
            model_name="pageconfig",
            name="title",
            field=models.CharField(
                default=1,
                help_text="título da página",
                max_length=200,
                verbose_name="Título",
            ),
            preserve_default=False,
        ),
    ]
