# Generated by Django 4.0.3 on 2022-05-28 22:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_alter_homepageconfig_church"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepageconfig",
            options={
                "verbose_name": "Configuração da Página Principal",
                "verbose_name_plural": "Configurações da Página Principal",
            },
        ),
        migrations.RemoveField(
            model_name="homepageconfig",
            name="body_content",
        ),
        migrations.RemoveField(
            model_name="homepageconfig",
            name="body_title",
        ),
        migrations.RemoveField(
            model_name="homepageconfig",
            name="content",
        ),
        migrations.RemoveField(
            model_name="homepageconfig",
            name="title",
        ),
        migrations.AlterField(
            model_name="churchbodysection",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="config.homepageconfig",
            ),
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Página principal"), (2, "Ministérios")],
                        help_text="Tipo de página",
                        verbose_name="Tipo de página",
                    ),
                ),
                (
                    "content_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Seção dos pastores"),
                            (11, "Seção dos ministérios"),
                        ],
                        help_text="Tipo de conteúdo",
                        verbose_name="Tipo de conteúdo",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="título do conteúdo",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Conteúdo"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.homepageconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo da Página",
                "verbose_name_plural": "Conteúdos da Página",
            },
        ),
        migrations.CreateModel(
            name="MinistryChurch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Nome completo"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.homepageconfig",
                    ),
                ),
            ],
            options={
                "ordering": ("page", "order"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactMeans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "whatsapp"),
                            ("email", "email"),
                            ("facebook", "facebook"),
                        ],
                        max_length=30,
                        verbose_name="Forma de contato",
                    ),
                ),
                (
                    "contact",
                    models.CharField(max_length=200, verbose_name="Contato"),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.ministrychurch",
                    ),
                ),
            ],
        ),
    ]
