# Generated by Django 4.0.3 on 2022-05-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0003_church_active"),
        ("config", "0007_alter_homepageconfig_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinistryPageConfig",
            fields=[],
            options={
                "verbose_name": "Configuração da Página dos Ministérios",
                "verbose_name_plural": "Configurações da Páginas dos Ministérios",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("config.homepageconfig",),
        ),
        migrations.AlterModelOptions(
            name="pagecontent",
            options={
                "ordering": ["page_type", "content_type"],
                "verbose_name": "Conteúdo da Página",
                "verbose_name_plural": "Conteúdos da Página",
            },
        ),
        migrations.AlterField(
            model_name="homepageconfig",
            name="church",
            field=models.ForeignKey(
                blank=True,
                help_text="Igreja ao qual a configuração estará associada",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_config",
                to="church.church",
                verbose_name="Igreja",
            ),
        ),
    ]
