# Generated by Django 4.0.3 on 2022-04-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="resume",
            field=models.TextField(
                blank=True,
                help_text="Breve resumo",
                max_length=1000,
                null=True,
                verbose_name="Resumo",
            ),
        ),
    ]
