# Generated by Django 4.0.3 on 2022-04-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alameda", "ALAMEDA"),
                    ("avenida", "AVENIDA"),
                    ("chacara", "CHACARA"),
                    ("condominio", "CONDOMÍNIO"),
                    ("conjunto", "CONJUNTO"),
                    ("estrada", "ESTRADA"),
                    ("ladeira", "LADEIRA"),
                    ("largo", "LARGO"),
                    ("parque", "PARQUE"),
                    ("praca", "PRAÇA"),
                    ("praia", "PRAIA"),
                    ("quadra", "QUADRA"),
                    ("rodovia", "RODOVIA"),
                    ("rua", "RUA"),
                    ("travessa", "TRAVESSA"),
                    ("via", "VIA"),
                ],
                max_length=100,
                null=True,
                verbose_name="Tipo de endereço",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="complement",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Complemento",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="País"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Rua"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Endereço de email"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Homem"), (1, "Mulher"), (2, "-")],
                default=2,
                null=True,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_main_contact",
            field=models.BooleanField(
                default=False, verbose_name="É o contato principal"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=17, null=True, verbose_name="Telefone"
            ),
        ),
    ]
