# Generated by Django 4.0.3 on 2022-04-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="maps_frame",
            field=models.TextField(
                blank=True, null=True, verbose_name="Iframe do Google Maps"
            ),
        ),
    ]
