# Generated by Django 4.0.3 on 2022-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMeans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "whatsapp"),
                            (2, "email"),
                            (3, "facebook"),
                            (4, "instagram"),
                            (5, "phone"),
                        ],
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "contact",
                    models.CharField(max_length=200, verbose_name="Contato"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Público"),
                ),
            ],
            options={
                "verbose_name": "Forma de Contato",
                "verbose_name_plural": "Formas de Contato",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="biografy",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biografia"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_media",
            field=models.ManyToManyField(
                blank=True,
                related_name="profile",
                to="account.contactmeans",
                verbose_name="Mídias Sociais",
            ),
        ),
    ]
