# Generated by Django 4.0.3 on 2022-04-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0002_alter_address_options_alter_address_address_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="address",
            table="account_address",
        ),
    ]
