# Generated by Django 4.0.3 on 2022-05-29 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_contactmeans_remove_customuser_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="social_media",
        ),
        migrations.AddField(
            model_name="contactmeans",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
            preserve_default=False,
        ),
    ]
