# Generated by Django 4.0.3 on 2022-05-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0002_church_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Ativa"),
        ),
    ]
