# Generated by Django 4.0.3 on 2022-05-29 20:17

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("church", "0002_ministry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchMinistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Usado para identificar o tipo de membro",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ministério da Igreja",
                "verbose_name_plural": "Ministérios da Igreja",
            },
        ),
        migrations.RemoveField(
            model_name="ministry",
            name="description",
        ),
        migrations.AlterField(
            model_name="membertype",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="ministry",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Líder",
            ),
        ),
        migrations.AlterField(
            model_name="ministry",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nome do lider",
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="ministry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="church.churchministry",
                verbose_name="Ministério da Igreja",
            ),
            preserve_default=False,
        ),
    ]
